version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      replicas: 1

  auth:
    image: cyberadvance/authen-service
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/auth
    deploy:
      replicas: 1

  addresss:
    image: cyberadvance/reservations-address-service
    ports:
      - "3003:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/addresss
    deploy:
      replicas: 1

  shops:
    image: cyberadvance/reservations-shops-service
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/shops
    deploy:
      replicas: 1

  web:
    image: cyberadvance/reservations-gateway-apis
    ports: 
      - "80:80"
    depends_on:
      - auth
      - shops
      - addresss
    deploy:
      replicas: 1  
      